# Generated by Django 2.2 on 2020-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200227_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product-', max_length=100),
        ),
    ]
