# Generated by Django 2.2 on 2020-02-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200227_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Clothes'), ('Fw', 'Footwear'), ('Te', 'Technology'), ('Ty', 'Toys'), ('To', 'Tools'), ('Od', 'Outdoors'), ('Pe', 'Pets'), ('Ve', 'Vehicles')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
